url: "https://whycoffee.blog"
baseurl: ""
title: "whycoffee.blog"
lang: "zh-Hant-TW"
permalink: /:categories/:title
future: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  # Default for all files
  -
    scope:
      path: ""
    values:
      toc: true
      language: zh-Hant-TW
  # English content (any path containing 'en/')
  -
    scope:
      path: "**/en/**"
    values:
      language: en
      locale: en_US
  # English posts need special permalink
  -
    scope:
      path: "_posts/en"
    values:
      permalink: 'en/:categories/:title'
  # Drafts and tag pages excluded from sitemap
  -
    scope:
      path: "_drafts"
    values:
      sitemap: false
  -
    scope:
      path: "tag"
    values:
      sitemap: false
  -
    scope:
      path: "en/tag"
    values:
      sitemap: false

exclude:
  - assets/archived/*
  - assets/scripts/*